# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 11155111
  start_block: 0
  contracts:
  - name: LiquidityHub
    address:
    - 0xF917A82B746bF161376D180A235f2515D3B438BD
    handler: src/EventHandlers.ts
    events:
    - event: RebalanceFinished(uint256 navBeforeRebalance, uint256 newNav)
    - event: Issue(address indexed issuer, address indexed recipient, uint256 assetAmount, uint256 receiptAmount)
    - event: InstantRedeem(address indexed redeemer, address indexed recipient, uint256 receiptAmount, uint256 assetAmount)
    - event: RedeemRequest(uint256 requestId, address indexed redeemer, address indexed recipient, uint256 receiptAmount)
    - event: Redeem(uint256 requestId, address indexed recipient, uint256 assetAmount);
  - name: sqUSD
    address:
    - 0x16b0191DB14c73f1133a5D4C23127318Fe9a7852
    handler: src/EventHandlers.ts
    events:
    - event: Transfer(address indexed from, address indexed to, uint256 amount)
    - event: Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)
    - event: Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets,uint256 shares)
field_selection:
  transaction_fields:
    - transactionIndex
    - hash
unordered_multichain_mode: true
preload_handlers: true