# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 11155111
  start_block: 0
  contracts:
  - name: LiquidityHub
    address:
    - 0xEe1047a2CEDb1aFc42ECd088DCBAAcD9f06529B4
    handler: src/EventHandlers.ts
    events:
    - event: RebalanceStarted(uint256 deployedUnderlying)
    - event: RebalanceFinished(uint256 deployedUnderlying)
    - event: RedeemsProcessed(uint256 lastProcessedRedeemId)
    - event: Issue(address indexed issuer, address indexed recipient, uint256 underlyingAmount, uint256 assetAmount)
    - event: InstantRedeem(address indexed redeemer, address indexed recipient, uint256 assetAmount, uint256 underlyingAmount)
    - event: RedeemRequest(uint256 redeemId, address indexed redeemer, address indexed recipient, uint256 assetAmount)
    - event: RedeemClaim(uint256 redeemId, address indexed recipient, uint256 underlyingAmount)
  - name: sqUSD
    address:
    - 0x4aBeD8353213656fda42406b9dA3d9CC3951Ae18
    handler: src/EventHandlers.ts
    events:
    - event: Transfer(address indexed from, address indexed to, uint256 amount)
    - event: Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)
    - event: Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets,uint256 shares)
  - name: Router
    address:
    - 0x35Df3B114ab69175652C3765Ec59b8E2915Dc2E2
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(address user, bool staked)
    - event: Withdraw(address user, bool unstaked, bool instant)

field_selection:
  transaction_fields:
    - transactionIndex
    - hash
unordered_multichain_mode: true
preload_handlers: true