type Rebalance {
  id: ID!
  timestamp: Int! @index
  oldNav: BigInt!
  newNav: BigInt!
  totalShares: BigInt!
}

type ShareBalanceSnapshot {
  id: ID!
  timestamp: Int! @index
  address: String! @index
  amount: BigInt!
}

type ShareBalance {
  id: ID!
  updatedAt: Int!
  amount: BigInt!
}

enum ActionType {
      ISSUE
      REDEEM
      INSTANT_REDEEM
      STAKE
      UNSTAKE
}

type Action {
  id: ID!
  address: String! @index
  actionType: ActionType!
  timestamp: Int!
  txHash: String!
  tokenIn: String!
  amountIn: BigInt!
  tokenOut: String!
  amountOut: BigInt!
}

type RedeemQueue {
  id: ID!
  requestsTotal: Int!
  requestsProcessed: Int!
  amountTotal: BigInt!
  amountProcessed: BigInt!
}

type RedeemRequest {
  id: ID!
  requestedAt: Int!
  requestTxHash: String!
  redeemer: String!
  recipient: String! @index
  amount: BigInt!
  isProcessed: Boolean! @index
}