type Rebalance {
  id: ID!
  timestamp: Int @index
  startRebalanceTxHash: String!
  deployedUnderlyingBefore: BigInt!
  endRebalanceTxHash: String
  deployedUnderlyingAfter: BigInt
  totalShares: BigInt
}

type ShareBalanceSnapshot {
  id: ID!
  timestamp: Int! @index
  address: String! @index
  amount: BigInt!
}

type ShareBalance {
  id: ID!
  updatedAt: Int!
  amount: BigInt!
}

enum ActionType {
      ISSUE
      REDEEM
      INSTANT_REDEEM
      STAKE
      UNSTAKE
}

type Action {
  id: ID!
  address: String! @index
  actionType: ActionType!
  timestamp: Int!
  txHash: String!
  tokenIn: String!
  amountIn: BigInt!
  tokenOut: String!
  amountOut: BigInt!
}

type RedeemQueue {
  id: ID!
  redeemsCount: Int!
  processedRedeemsCount: Int!
  redeemAssets: BigInt!
  processedRedeemAssets: BigInt!
}

type RedeemRequest {
  id: ID!
  requestedAt: Int!
  requestTxHash: String!
  redeemer: String!
  recipient: String! @index
  amount: BigInt!
  isProcessed: Boolean! @index
}